### ISSUE TITLE
building with swiftc no output

### ISSUE THREAD

**Issue by Celerrime** [FedoraSwift/fedora-swift2#1]
Building swift program with swiftc not working for me using latest swift 3 on f25.

`echo 'print("Hello World!") > main.swift && swiftc main.swift'`

expecting a binary that I can run using ./main

instead the command passes silently with no output file in my working directory.

**Comment by thawkins** [comment]
try

echo 'print("Hello World!")' > main.swift && swiftc main.swift

produces main.swift and compiles to main

>[thawkins@timdev05 ~]$ cd ~/tmp
> [thawkins@timdev05 tmp]$ echo 'print("Hello World!") > main.swift && swiftc main.swift'
> print("Hello World!") > main.swift && swiftc main.swift
> [thawkins@timdev05 tmp]$ 
> [thawkins@timdev05 tmp]$ echo 'print("Hello World!")' > main.swift && swiftc main.swift
> [thawkins@timdev05 tmp]$ ls
> main.swift     main
> [thawkins@timdev05 tmp]$ ./main
> Hello World!
> [thawkins@timdev05 tmp]$
